### ISSUE TITLE
为什么我本地mkdir会有权限问题？需要怎么做呢

### ISSUE THREAD

**Issue by ilolicon** [KagurazakaNyaa/palworld-docker#10]
Step 20/23 : RUN mkdir -p /opt/palworld/Pal/Saved
 ---> Running in b23422cca3bf
mkdir: cannot create directory '/opt/palworld/Pal': Permission denied

**Comment by KagurazakaNyaa** [comment]
我没有遇到过这样的问题，无论是在Github Actions里自动构建还是我在本地用docker compose build手动构建镜像都是正常的
也许你可以检查一下你的Dockerfile是不是被修改过，看看上面有没有修改USER的步骤

**Comment by ilolicon** [comment]
我换ubuntu 22.04构建没问题了 之前用的centos 7.x 不确定具体什么问题
