### ISSUE TITLE
Output game server logs to docker logs

### ISSUE THREAD

**Issue by C0Nd3Mnd** [KagurazakaNyaa/palworld-docker#12]
This container currently doesn't seem to output any game server output to docker logs. I can only see the output of `steamcmd`. The server is running fine, just no game server logs with `docker logs <container_name>`.

**Comment by KagurazakaNyaa** [comment]
The game server itself does not provide log output to stdout, nor is it configurable, nor is it written to a log file, so it is impossible for me to print out the server log.
