### ISSUE TITLE
Update Patch v0.1.4.1

### ISSUE THREAD

**Issue by pcyang** [KagurazakaNyaa/palworld-docker#20]
The latest update just came out a bit over an hour ago, could you update the `currentversion` to the latest?

2024/02/07 Update Patch v0.1.4.1 (18:57 PST)
https://store.steampowered.com/news/app/1623730/view/4013339239712681243

It seems like I'm able to workaround by setting `FORCE_UPDATE` to unblock myself, but changing it back would immediately downgrade it back again.

Thanks!

**Comment by KagurazakaNyaa** [comment]
The update check has been triggered manually and a new image has been built

**Comment by pcyang** [comment]
Thank you!
