### ISSUE TITLE
Is the PalWorldSettings.ini supposed to be blank?

### ISSUE THREAD

**Issue by RiffyDivine** [KagurazakaNyaa/palworld-docker#3]
I got this up and running without any issues but I wanted to mess around with the config some. I noticed that the PalworldSettings.ini file that should be populated is blank. Is that intended? As it is used to set the server settings according to the docs from Palworld.

**Comment by atajsic** [comment]
There is an example file in the root directory of the palserver. I've copy-pasted it below;

`DefaultPalWorldSettings.ini`

`; This configuration file is a sample of the default server settings.
; Changes to this file will NOT be reflected on the server.
; To change the server settings, modify Pal/Saved/Config/WindowsServer/PalWorldSettings.ini.
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=False,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
`

Simply copy and past this into your `PalworldSettings.ini` file and change the values.

**Comment by KagurazakaNyaa** [comment]
Yes, this directory is automatically created by the palworld server. Currently, you need to manually copy the content from `DefaultPalWorldSettings.ini`. For modifiable content, please refer to https://tech.palworldgame.com/optimize-game-balance
I will automate this process of initialization and copying the default value content in future versions, and also initialize some commonly used configurations with environment variables.

**Comment by yokaimeow** [comment]
thk

**Comment by KagurazakaNyaa** [comment]
Pull the latest image and the configuration file should be created normally.

**Comment by RiffyDivine** [comment]
Thanks, I had figured it out and just forgot to come back and update. Sorry about that.
