### ISSUE TITLE
提问 请问如何更新服务器版本

### ISSUE THREAD

**Issue by AlanBacker** [KagurazakaNyaa/palworld-docker#8]
请问如何更新服务器版本？我目前系统是Debian

**Comment by KagurazakaNyaa** [comment]
`docker compose pull && docker compose up -d`
或者在环境变量里设置`FORCE_UPDATE=true`

**Comment by lxonz** [comment]
如何进行更新，怕存档g了，在docker中安装steamcmd并不能下载最新版本的游戏

**Comment by AlanBacker** [comment]
> `docker compose pull && docker compose up -d` 或者在环境变量里设置`FORCE_UPDATE=true`

十分感谢

**Comment by AlanBacker** [comment]
> `docker compose pull && docker compose up -d` 或者在环境变量里设置`FORCE_UPDATE=true`

执行了之后出现了这个问题，目前在home folder下
# docker compose pull && docker compose up -d
no configuration file provided: not found

**Comment by bryanroscoe** [comment]
If you mounted your save directory and it is safe then you can just 

```
docker compose down
docker image rm yourimageid`
docker compose up
```
and then it should be all good.

**Comment by KagurazakaNyaa** [comment]
> > `docker compose pull && docker compose up -d` 或者在环境变量里设置`FORCE_UPDATE=true`
> 
> 执行了之后出现了这个问题，目前在home folder下
> # docker compose pull && docker compose up -d
> 
> no configuration file provided: not found

也许你是直接使用`docker run`方式跑起来的，那你如果之前没有挂载，现在就要用`docker cp`把卷里的存档拷贝到宿主机然后再重新创建容器
